apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: furlan-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: igf-space
  project: default  
  source:
    repoURL: 'https://github.com/igfurlan/deploy-app.git'
    path: application-helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true